#ifndef LS_SEQUENCES_H
#define LS_SEQUENCES_H

#define FSH(x) (__FlashStringHelper*)(x)
#include "lsSequenceFill.h"
#include "lsSequenceScan.h"
#include "lsSequenceConfetti.h"
#include "lsSequenceLightning.h"
#include "lsSequenceGlitter.h"
#include "lsSequenceSparkle.h"
#include "lsSequenceBPM.h"
#include "lsSequenceSinelon.h"
#include "lsSequenceStrobe.h"
#include "lsSequenceColorBars.h"
#include "lsSequenceBeat8Tail.h"
#include "lsSequenceCellularNoise.h"
#include "lsSequenceTargetA.h"
#include "lsSequenceTargetB.h"
#include "lsSequencePopupDroid.h"
#include "lsSequenceBouncingBars.h"
#include "lsSequenceBouncingBar.h"
#include "lsSequenceComet.h"
#include "lsSequenceElectricity.h"
#include "lsSequenceJuggle.h"
#include "lsSequencePaletteBreathe.h"
#include "lsSequencePaletteDissolve.h"
#include "lsSequencePaletteGradient.h"
#include "lsSequencePaletteWave.h"
#include "lsSequenceSparkles.h"
#include "lsSequenceTeatherChase.h"
#include "lsSequenceWanderingLine.h"
#include "lsSequenceBlink.h"
#include "lsSequenceWipe.h"
#include "lsSequenceSingleDynamic.h"
#include "lsSequenceSweep.h"
#include "lsSequenceFillUp.h"
#include "lsSequenceTetris.h"
#include "lsSequenceSandWatch.h"
#include "lsSequenceAndroid.h"
#include "lsSequenceAurora.h"
#include "lsSequenceGroup.h"
#include "lsSequenceDigitalRain.h"
//#include "lsSequenceStarShower.h" verificare trail decay
//#include "lsSequenceFeathers.h"
//#include "lsSequenceCandyCane.h"
//#include "lsFilterBlurSequence.h"
//#include "lsFilterRGBSequence.h"


#endif
